### ISSUE TITLE
Allow for TRESBillingWeights 

### ISSUE THREAD

**Issue by Falkor** [ULHPC/puppet-slurm#16]
See [Trackable RESources (TRES)](https://slurm.schedmd.com/tres.html). 

Associated directives: 

```
AccountingStorageTRES
PriorityWeightTRES
TRESBillingWeights
```

**Comment by Falkor** [comment]
Ex of hiera config: 

```yaml
# Which Trackable RESources (TRES) will be tracked in addition to
# billing, cpu, energy, memory and node
slurm::accountingstoragetres: gres/gpu,gres/gpu:volta
slurm::priorityweighttres:    CPU=1000,Mem=2000,GRES/gpu=300

slurm::partitions:
  'DEFAULT':
    TRESbillingweights: 'CPU=1.0,Mem=0.25G,GRES/gpu=15.0'
    content: State=UP AllowGroups=clusterusers AllowAccounts=ALL DisableRootJobs=YES OverSubscribe=NO
  'admin':
    priority: 100
    nodes: 'node-[1-2]'
    content: Hidden=YES DefaultTime=0-10:00:00 MaxTime=5-00:00:00 MaxNodes=UNLIMITED  AllowQos=qos-admin
  'interactive':
    priority: 20
    nodes: 'node-1'
    content: DefaultTime=0-1:00:00  MaxTime=0-4:00:00  AllowQos=qos-besteffort,qos-interactive DefMemPerCPU=400 MaxMemPerCPU=400
  'batch':
    priority: 20
    nodes: 'node-[2-2]'
    content: DefaultTime=0-2:00:00  MaxTime=5-00:00:00 MaxNodes=UNLIMITED Default=YES AllowQos=qos-besteffort,qos-batch DefMemPerCPU=400 MaxMemPerCPU=400
```
