### ISSUE TITLE
when using external DB, we enable outside connections to local DB

### ISSUE THREAD

**Issue by jorhett** [ULHPC/puppet-slurm#74]
If you configure an external database for Slurm, Puppet is changing the local (totally unrelated!) mysql instance to allow external connections:

```
Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/content:
--- /etc/my.cnf.d/server.cnf	2024-08-15 20:22:05.110172179 +0000
+++ /tmp/puppet-file20240815-170215-gwhbun	2024-08-15 20:41:20.534894953 +0000
@@ -11,7 +11,7 @@

 [mysqld]
 basedir = /usr
-bind-address = 127.0.0.1
+bind-address = 0.0.0.0
 datadir = /var/lib/mysql
 innodb_buffer_pool_size = 256M
 innodb_lock_wait_timeout = 500
```

Resolved configuration looks like this:

```shell
# grep Storage /etc/slurm/slurmdbd.conf
StorageType=accounting_storage/mysql
StorageHost=10.10.10.10
StoragePort=3306
StorageLoc=slurm   # Name of the database
StorageUser=slurm-user
StoragePass=*************
```

**Comment by m8t** [comment]
The module should not at any moment permit the bootstrapped MySQL instance to bind on anything else than the loopback. Since it is installed locally with slurmdbd.

Otherwise, you would just want to not bootstrap and manage MySQL on the same host as slurmdbd.

If the feature would be required to customize the bootstrapped MySQL instance binding port, we can add a specific class attribute to slurm::slurmdbd I think. So let's just remove this condition and keep 127.0.0.1.

**Comment by m8t** [comment]
Also if you want to add replication with a secondary MySQL instance, the module slurm is not adequate.

Example of hiera for the module mysql with just `include mysql::server` inside a manifest:
```yaml
# MariaDB with replica options
slurm::slurmdbd::bootstrap_mysql: false
mysql::server::override_options:
  mysqld:
    bind-address: '0.0.0.0'
    # For replication
    server-id: define at hiera level for nodes
    log-bin: 'mariadb-bin'
    binlog-format: 'mixed'
    # InnoDB settings
    innodb_buffer_pool_size:  '22G'
    innodb_log_file_size: '256M'
    innodb_lock_wait_timeout: 900
```
